[package]
name = "munge-rs"
version = "0.1.0"
edition = "2021"
description = "Rust FFI binding for MUNGE Uid 'N' Gid Emporium"

build = "build.rs"


[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.69.4"
