[package]
name = "munge-rs"
version = "0.1.1"
edition = "2021"
description = "Rust FFI binding for MUNGE Uid 'N' Gid Emporium"

build = "build.rs"


[dependencies]
libc = "0.2"
thiserror = "1.0"
num_enum = "0.7"
chrono = "0.4"

[build-dependencies]
bindgen = "0.69.4"
